baseURL: https://codecoffeeclimb.github.io/
languageCode: en-us
title: Code Coffee Climb
theme: PaperMod
publishDir: docs

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10
params:
  ShowShareButtons:  true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  homeInfoParams:
    Title: Code Coffee Climb ☕
    Content: >
        Welcome to my blog. I write articles about programming for grown ups and kids. 
        I also enjoy drinking coffee and doing rock climbing. Hope you will enjoy. Cheers!
  socialIcons:
    - name: github
      url: https://github.com/codecoffeeclimb
    - name: RsS
      url: index.xml
    - name: youtube
      url: https://www.youtube.com/channel/UCiEldrWJU5aA7LfR-AuoEaQ
    # ![Coffee Beans](/images/coffeebean.jpeg)
outputs:
  home: 
    - HTML
    - RSS
    - JSON