baseURL: https://codecoffeeclimb.github.io/
languageCode: en-us
title: Code Coffee Climb
theme: PaperMod
publishDir: docs

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true
    # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10

outputs:
  home: 
    - HTML
    - RSS
    - JSON

params:
  env: production

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

  homeInfoParams:
    Title: Code Coffee Climb ☕
    Content: >
        Welcome to my blog. I write articles about programming for grown ups and kids. 
        I also like drinking coffee and rock climbing. Hope you will enjoy this blog. Cheers!
  socialIcons:
    - name: github
      url: https://github.com/codecoffeeclimb
    - name: RsS
      url: index.xml
    - name: youtube
      url: https://www.youtube.com/channel/UCiEldrWJU5aA7LfR-AuoEaQ
    # ![Coffee Beans](/images/coffeebean.jpeg)

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
